export default function FakeData() {
  const fakeData = {
    results: [
      {
        id: "Ubg08UXH44VkAxTbd1OF",
        data: {
          source: null,
          date: "14/09/2023 11:51:07",
          exact_position: null,
          confirmation_count: 8,
          location: "دوار امزاورو جماعة تويالت قيادة اسكاون عمالة ترودانت",
          id: null,
          dis_confirmation_count: 3,
          details: "مبيت في العراء، منازل مهددة بالسقوط ",
          position_static: null,
          docId: "Ubg08UXH44VkAxTbd1OF",
          city: "تارودانت",
          contact: {
            phone_number: "616360764",
          },
          needs: ["مأوى", "طعام وماء"],
          in_place: false,
        },
      },
      {
        id: "9PRe3eTyD6e7twNQ38cb",
        data: {
          contact: {
            phone_number: '"(212)661351982 محمد ايت محمد "',
          },
          date: "13/09/2023 16:47:03",
          exact_position: {
            longitude: -7.675463110589399,
            latitude: 31.225559234559128,
          },
          id: null,
          in_place: false,
          docId: "9PRe3eTyD6e7twNQ38cb",
          location: "Setti-Fatma",
          dis_confirmation_count: 5,
          source: null,
          confirmation_count: 8,
          city: "Haouz",
          details: "Very Very critical situation",
          needs: ["طعام وماء", "أغطية وملابس"],
          position_static: {
            latitude: 31.225559234559128,
            longitude: -7.675463110589399,
          },
        },
      },
      {
        id: "BkGXWa8CjBZfD7LT6WEX",
        data: {
          confirmation_count: 7,
          in_place: true,
          position_static: null,
          dis_confirmation_count: 4,
          city: "تارودانت",
          id: null,
          contact: {
            phone_number: "0672203639",
          },
          needs: ["مأوى"],
          date: "14/09/2023 14:41:34",
          docId: "BkGXWa8CjBZfD7LT6WEX",
          exact_position: null,
          source: null,
          details: null,
          location: "تافراوتن قيادة تملوكت ",
        },
      },
      {
        id: "0ihqlDLa01TUtJbh5Z0n",
        data: {
          date: "14/09/2023 16:46:24",
          position_static: null,
          docId: "0ihqlDLa01TUtJbh5Z0n",
          city: "ايمينتانوت، شيساوة",
          id: null,
          confirmation_count: 3,
          exact_position: null,
          contact: {
            phone_number:
              "0691833904  عبد الله ، امام مسجد الدوار، ، رقم آخره عند الضرورة 0661476147.",
          },
          location: "إقليم شيشاوة *الجماعة القروية آيت حدو يوسف دوار أسيف لحلو",
          source: "إمام و أستاذ الدوار",
          details: null,
          in_place: true,
          needs: ["مأوى", "طعام وماء"],
        },
      },
      {
        id: "AgBdFxrIQZFfbAMCRJMe",
        data: {
          details: null,
          id: null,
          location: "دوار تورتيت جماعة خزامة إقليم ورزازات ",
          confirmation_count: 2,
          docId: "AgBdFxrIQZFfbAMCRJMe",
          needs: ["مساعدة طبية"],
          city: "ورزازات",
          contact: {
            phone_number: null,
          },
          dis_confirmation_count: 1,
          position_static: null,
          in_place: true,
          source: null,
          exact_position: null,
          date: "14/09/2023 18:47:11",
        },
      },
      {
        id: "0oGi1e9UD4qG7p3ofgO3",
        data: {
          needs: ["إغاثة", "مساعدة طبية", "مأوى", "طعام وماء"],
          location: "ايت يونس تيديلي ",
          id: null,
          source: null,
          position_static: null,
          date: "13/09/2023 20:17:56",
          details: "حالة بورت لها",
          dis_confirmation_count: 2,
          contact: {
            phone_number: "0680645218",
          },
          docId: "0oGi1e9UD4qG7p3ofgO3",
          city: "ورزازات ",
          confirmation_count: 2,
          exact_position: null,
          in_place: true,
        },
      },
      {
        id: "2m7HC4LrKedjvGHzMkxN",
        data: {
          city: "الصويرة",
          contact: {
            phone_number: null,
          },
          in_place: true,
          needs: ["طعام وماء"],
          details:
            "ناس راه مكرفصين هنا را كايباتو غي على برا كلشي تريب ديور مريبين  كاملين مكاينش لماء ولا الغطاء باش اتغطاو من البرد ",
          source: null,
          id: null,
          exact_position: null,
          location: "دوار تيزي جماعة اسايس قيادة ادغاس ",
          docId: "2m7HC4LrKedjvGHzMkxN",
          date: "13/09/2023 19:16:33",
          confirmation_count: 2,
          position_static: null,
        },
      },
      {
        id: "7sxZN1a66UcZfDJr4TsX",
        data: {
          dis_confirmation_count: 1,
          city: "مراكش",
          date: "14/09/2023 15:21:04",
          details: null,
          in_place: true,
          docId: "7sxZN1a66UcZfDJr4TsX",
          id: null,
          needs: ["مأوى"],
          confirmation_count: 1,
          source: null,
          contact: {
            phone_number: null,
          },
          position_static: null,
          exact_position: null,
          location:
            "دوار تاركة أوفلا جماعة أيت حدو يوسف قيادة سكساوة إقليم شيشاوة ",
        },
      },
      {
        id: "FlWlzn9vDqRQ8MFIoIDi",
        data: {
          id: null,
          source: null,
          details: null,
          city: "تارودانت",
          dis_confirmation_count: 2,
          docId: "FlWlzn9vDqRQ8MFIoIDi",
          confirmation_count: 1,
          position_static: null,
          contact: {
            phone_number: "0662029411 تلامت تازيايت",
          },
          needs: [],
          in_place: false,
          date: "14/09/2023 15:20:22",
          exact_position: null,
          location: "جماعات اداݣايلال قيادات إݣلي",
        },
      },
    ],
    lastKey: "14/09/2023 15:20:22",
    firstKey: "14/09/2023 11:51:07",
    lastCount: 1,
    firstCount: 8,
  };
  return fakeData;
}
